// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs-SD0EAwT9KLjczAU3E3z98zGE6-mW5A',
    appId: '1:167893065881:android:f1e7eedad57ddcacb6d808',
    messagingSenderId: '167893065881',
    projectId: 'eat-experts',
    storageBucket: 'eat-experts.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAdY8qv_E--V5mhRURfyEv-wpV4qoUDZM',
    appId: '1:167893065881:ios:ed69e63c1c0d5eebb6d808',
    messagingSenderId: '167893065881',
    projectId: 'eat-experts',
    storageBucket: 'eat-experts.appspot.com',
    iosClientId: '167893065881-b7clsvrdnfvllrhao2anhtbe7rk44h04.apps.googleusercontent.com',
    iosBundleId: 'com.example.eatexperts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAdY8qv_E--V5mhRURfyEv-wpV4qoUDZM',
    appId: '1:167893065881:ios:ed69e63c1c0d5eebb6d808',
    messagingSenderId: '167893065881',
    projectId: 'eat-experts',
    storageBucket: 'eat-experts.appspot.com',
    iosClientId: '167893065881-b7clsvrdnfvllrhao2anhtbe7rk44h04.apps.googleusercontent.com',
    iosBundleId: 'com.example.eatexperts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpCMUl6IMxuKQGfNxrklBDFx4qpN02YjU',
    appId: '1:167893065881:web:1eacd892ff39aa36b6d808',
    messagingSenderId: '167893065881',
    projectId: 'eat-experts',
    authDomain: 'eat-experts.firebaseapp.com',
    storageBucket: 'eat-experts.appspot.com',
  );
}
