// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuWubuVdsH8RNmKM2LcNejYlGlGXpjHZk',
    appId: '1:139251597451:android:cbd6c124b9be1ecc54548e',
    messagingSenderId: '139251597451',
    projectId: 'eatexperts-d4098',
    storageBucket: 'eatexperts-d4098.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAznZrJx5xX0m7t6a-XC3l2ShrqMfwUT9w',
    appId: '1:139251597451:ios:f7af7ac7c79b8bf654548e',
    messagingSenderId: '139251597451',
    projectId: 'eatexperts-d4098',
    storageBucket: 'eatexperts-d4098.appspot.com',
    iosBundleId: 'com.example.eatexperts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAznZrJx5xX0m7t6a-XC3l2ShrqMfwUT9w',
    appId: '1:139251597451:ios:f7af7ac7c79b8bf654548e',
    messagingSenderId: '139251597451',
    projectId: 'eatexperts-d4098',
    storageBucket: 'eatexperts-d4098.appspot.com',
    iosBundleId: 'com.example.eatexperts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3K6_4S9AqoBgAP1YgFO3iPJG_xZGlGPg',
    appId: '1:139251597451:web:0f6412df2024a59954548e',
    messagingSenderId: '139251597451',
    projectId: 'eatexperts-d4098',
    authDomain: 'eatexperts-d4098.firebaseapp.com',
    storageBucket: 'eatexperts-d4098.appspot.com',
    measurementId: 'G-FPSRF9DQHN',
  );

}